spring:
  application: 
    name: eureka-server
    
#server:
#  port: 2001
  
eureka:
  server:
    enable-self-preservation: false   
    #eureka 的自我保护状态：心跳失败的比例，在15分钟内是否低于85%,如果出现了低于的情况，Eureka Server会将当前的实例注册信息保护起来，同时提示一个警告，一旦进入保护模式，Eureka Server将会尝试保护其服务注册表中的信息，不再删除服务注册表中的数据。也就是不会注销任何微服务
#  instance:
#    hostname: eureka1
#  client:
#    register-with-eureka: false    #不向自身注册
#    fetch-registry: false    #不从自身拉取注册信息
    #lease-eexpiration-duration-in-seconds: 90   最后一次心跳后，间隔多久认定微服务不可用，默认90
    
  
---
spring:
  profiles: eureka1

server:
  port: 2001
  
# eureka1 向 eureka2 注册
eureka:
  instance:
    hostname: eureka1
  client:
    service-url: 
      defaultZone: http://eureka2:2002/eureka

---
spring:
  profiles: eureka2

server:
  port: 2002
  
# eureka2 向 eureka1 注册
eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka